.gitignore
static/themes/landscape/layout/_partial/head.ejs
static/themes/landscape/layout/event.ejs
static/themes/landscape/source/css/style.styl

#50 
reproduction prototype of event
close #50 
w3cssを使えるようにしました
http://memopad.bitter.jp/w3c/w3css/w3css_slideshow.html

イベントページのプロトタイプを再現しました

---

static/themes/landscape/layout/index.ejs

#56 
reproduction prototype of top
close #56

TOPでプロトタイプを再現しました

---

static/themes/landscape/layout/mogi-shop.ejs

#54 
reproduction prototype of mogi-shop
close #54 
検索機能は現状一個目のテーブルしか検索できないです．．

模擬店一覧ページでプロトタイプを再現しました

---

.gitignore
bot/account.json
bot/bot.js
bot/package.json
bot/shop.json
bot/utils.js
bot/views/_booth.ejs

jsonからhtmlファイルを生成できるようにしました

---

.gitignore
static/themes/landscape/layout/index.ejs
static/themes/landscape/layout/mogi-shop.ejs

模擬店とニュースでのjson読み込み
今はjsonはejsファイルに手打ちしてますがajaxか何かでurlからファイルを読み込むようにします
newsには今のところイベントだけ乗るようになてます
eventのjsonの形式の見直しが必要

load json data

---

.circleci/config.yml
setup.sh

#86 , #118 , #120 に関して
とりあえずdeployして、成功したときにメッセージをslackに送信するスクリプトを書いた
デプロイ先はcircleciの環境変数で管理
デプロイ後のスクリプトは `setup.sh` 
現在slackに送信のみしているが、今後はhexoのビルド、シンボリックリンクの配置まで行いたい
close #86 
close #118 
close #120

circleciを用いたテスト環境へのプログラムの配置

---

static/_config.yml
static/themes/landscape/_config.yml
static/themes/landscape/layout/_partial/header.ejs
static/themes/landscape/layout/mogi-shop.ejs
static/themes/landscape/source/css/_variables.styl
static/themes/landscape/source/css/style.styl

模擬店一覧の表示の変更（ちゃんと整列するようにしました
タイトルを英語に統一

chenge layout

---

static/themes/landscape/source/css/_variables.styl

バナーの画像を変更しました

---

static/themes/landscape/layout/event.ejs
static/themes/landscape/layout/index.ejs
static/themes/landscape/source/css/style.styl

スライドショーのバグを修正

---

static/themes/landscape/layout/mogi-shop.ejs
static/themes/landscape/source/css/style.styl

各模擬店からマップに飛ぶリンクを貼りました

---

static/themes/landscape/layout/index.ejs
static/themes/landscape/layout/mogi-shop.ejs
static/themes/landscape/source/css/style.styl

模擬店一覧のレイアウト変更

---

static/themes/landscape/_config.yml

ナビゲーションバーの修正

---

api-server/app.js
static/package-lock.json
static/package.json

fix router for api-server

---

api-server/routes/linebot.js
api-server/routes/shop-area.json

4jの中心に置いた場合，入口階段付近で反応した。
外での電波範囲の確認が必要
近くの模擬店（テンプレートメッセ）に関しては別のブランチを立てることにした

sun-yryr/beacon連携確認

---

static/themes/landscape/layout/index.ejs
static/themes/landscape/source/css/_variables.styl

I changed the path of icon inthe index.ejs

icon paths changed

---

static/themes/landscape/layout/index.ejs
static/themes/landscape/source/css/style.styl
static/themes/landscape/source/fancybox/jquery.skeduler.css
static/themes/landscape/source/fancybox/jquery.skeduler.js
static/themes/landscape/source/fancybox/skeduler.js

スマホ用の表示を修正

---

static/themes/landscape/layout/index.ejs
static/themes/landscape/source/css/style.styl

画像適用後の見た目のバグを修正

---

api-server/package.json
api-server/routes/linebot.js

- 来場者からも写真を集めたら面白いのでは！？
- フォトコンテストの下準備
- 10件同時に送信すると2件保存できない。削除でエラー吐いてるから保存が間に合ってないとかある？

[add] Download Image

---

api-server/routes/linebot.js

指定のurlにbodyくっつけてpostするとプッシュメッセージが送れる
パラメータがわかると誰でも送れてしまう

[add] LINE pushMessage

---

static/themes/landscape/layout/index.ejs
static/themes/landscape/source/css/_variables.styl

update banner and icons
MERGE RIGHT NOW F**KIN' S**T

Image test2

---

bot/bot.js
static/themes/landscape/source/css/style.styl

Sakakendo/i245 fix style
close #245

スクロールバー、divの左寄せを修正しました

---

bot/bot.js
static/themes/landscape/layout/event.ejs

fix jquery cdn

---

api-server/routes/beacondb.js

api-server/routes/beacondb.js
- updateのキーをplaceに変更しました
- updateで全て変更に対応しました

[change] beacon update

---

static/themes/landscape/layout/_partial/header.ejs
static/themes/landscape/source/css/_partial/header.styl

校章を右上に表示しました

---

static/themes/landscape/layout/mogi-shop.ejs

imageは全て「no image」になってます
imageのurlに日本語が入らないようにすれば表示できそう

模擬店の実際のデータを取得しました

---

static/themes/landscape/layout/gallery.ejs
static/themes/landscape/source/css/style.styl

add comment 'in preparation' on gallarey

---

static/themes/landscape/layout/mogi-shop.ejs
static/themes/landscape/source/css/style.styl

価格変更がわかるようにしました

---

static/themes/landscape/layout/gallery.ejs

雑に画像を全部上げた

---

static/themes/landscape/layout/mogi-shop.ejs

boothで"円"のみ表示されているバグを修正

---

static/themes/landscape/source/skeduler/jquery.skeduler.css
static/themes/landscape/source/skeduler/jquery.skeduler.js
static/themes/landscape/source/skeduler/skeduler.js

fix display on event

---

static/_config.yml
static/themes/landscape/_config.yml
static/themes/landscape/layout/_partial/header.ejs
static/themes/landscape/layout/_partial/mobile-nav.ejs
static/themes/landscape/source/css/_partial/header.styl
static/themes/landscape/source/css/_partial/mobile.styl
static/themes/landscape/source/css/_variables.styl
static/themes/landscape/source/css/style.styl

バナーのデザイン変更，ロゴの適用

---

static/themes/landscape/source/skeduler/skeduler.js

イベントで日付が変更できないエラーを解決

---

static/source/link/index.md
static/themes/landscape/_config.yml
static/themes/landscape/layout/_partial/footer.ejs
static/themes/landscape/layout/link.ejs
static/themes/landscape/source/css/_partial/footer.styl

リンクをフッターに移動

---

api-server/routes/labodata.json
api-server/routes/linebot.js
api-server/routes/mapdata.json

line bot機能の最終調整です。
画像の変更
利用方法などのメッセージの追加
コンサート（静的データ）の表示
D3ピン押しにく問題を修正しています（検証はまだ）
動作確認したいです。

D3のピンが押しにくい問題を修正しました。クラシカルコンサートのデータを追加しました。メッセージの最終調整を行いました。

---

api-server/routes/linebot.js
api-server/routes/useradd.json

下記参照
https://twitter.com/taittide/status/1052548451290861568

[add] Beaconの初回設定連絡

---

static/themes/landscape/layout/mogi-shop.ejs

fix layout,url

---

api-server/routes/linebot.js

docomo chat

---

bot/views/map_shop.ejs

#424 
> mapで表示されるinformationから「マップを表示」を消す #424
>> booth.jsonってラインのほうから呼び出してるように見えるけど大丈夫か
close #424

delete goto map of booth.json

---

api-server/routes/index.js

体育館関係を修正しました
